services:
  meiduo_server:
    build: ./meiduo_mall
    image: meiduo_server
    container_name: meiduo_server
    env_file: .env
    restart: always
    volumes:
      - ./meiduo_mall:/var/www/html/meiduo_mall:ro
      - ./data/logs:/var/log/meiduo
      - ./data/static:/var/www/html/static
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      es:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - meiduo_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthz/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3


  celery_worker:
    build: ./meiduo_mall
    image: meiduo_worker
    container_name: meiduo_worker
    env_file: .env
    command: celery -A celery_tasks.main worker -l info
    volumes:
      - ./meiduo_mall:/var/www/html/meiduo_mall:ro
      - ./data/logs:/var/log/meiduo
      - ./data/static:/var/www/html/static
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - meiduo_net


  meiduo_web:
    build: ./meiduo_mall_frontend
    image: meiduo_web
    container_name: meiduo_web
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - meiduo_server
    volumes:
      - ./meiduo_mall_frontend/dist:/usr/share/nginx/html:ro
      - ./meiduo_mall_frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - meiduo_net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/healthz/ || exit 1"]
      interval: 30s
      retries: 3



  redis:
    image: redis:4.0
    container_name: md_redis
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    networks:
      - meiduo_net


  es:
    image: delron/elasticsearch-ik:2.4.6-1.0
    container_name: md_es
    ports:
      - "9200:9200"
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    networks:
      - meiduo_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 5


  mysql:
    image: mysql:8.0
    container_name: md_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meiduo_mall
      TZ: Asia/Shanghai
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
    networks:
      - meiduo_net

networks:
  meiduo_net:
    driver: bridge

